apiVersion: v1
kind: Namespace
metadata:
    name: otus
    labels:
        name: otus
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: otus-hw-1
    namespace: otus
    labels:
        app: otus-hw-1
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: otus-hw-1
    template:
        metadata:
            labels:
                app: otus-hw-1
        spec:
            containers:
                - name: health-srv
                  image: docker.io/andreyovs/otus_hw1:1.0.0
                  ports:
                      - containerPort: 8000
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8000
                      initialDelaySeconds: 3
                      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
    name: health-service
    namespace: otus
spec:
    selector:
        app: otus-hw-1
    ports:
        - port: 8000
          targetPort: http
    type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: health
    namespace: otus
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: arch.homework
          http:
              paths:
                  - path: /(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: health-service
                            port:
                                number: 8000
